# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

stages:
  - sim

sim:
  stage: sim
  script:
    - /usr/local/anaconda3/bin/python vendor/lowrisc_opentitan/util/regtool.py src/test/test_regs.hjson -t src/test -r
    - git diff --exit-code
    - bender script vsim -t test -t register_interface_test --vlog-arg="-svinputport=compat" > compile.tcl
    - questa-2022.3 vsim -c -do 'exit -code [source compile.tcl]'
    - questa-2022.3 vsim -c tb_simple_registers -do "run -all"
