# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-license:
    name: Check license
    runs-on: ubuntu-latest
    steps:
      - uses: pulp-platform/pulp-actions/lint-license@v2
        with:
          license: |
            Copyright (\d{4}(-\d{4})?\s)?ETH Zurich and University of Bologna.
            Solderpad Hardware License, Version 0.51, see LICENSE for details.
            SPDX-License-Identifier: SHL-0.51
          # Exclude generated headers (no license checker support for optional lines)

  lint-verilog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chipsalliance/verible-linter-action@main
        with:
          paths: |
            ./src
            ./include
          extra_args: "--rules=-interface-name-style --lint_fatal --parse_fatal --waiver_files util/waiver.verible"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewdog_reporter: github-check

  internal:
    name: Internal CI
    runs-on: ubuntu-latest
    steps:
      - name: Mirror and check
        uses: pulp-platform/pulp-actions/gitlab-ci@v2
        # Skip on forks or pull requests from forks due to missing secrets.
        if: >
          github.repository == 'pulp-platform/obi' &&
          (github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository)
        with:
          domain: iis-git.ee.ethz.ch
          repo: github-mirror/obi
          token: ${{ secrets.GITLAB_TOKEN }}
